resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/ExitoLab/codementor_concourse_ci_azure.git
    branch: main

# Where we will push the image
- name: simple-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))/simple-image
    username: ((registry-username))
    password: ((registry-password))

jobs:
- name: build-and-sign-docker-image
  public: true
  plan:
  - get: source-code
    trigger: true

  - task: build
    privileged: false
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: source-code
        path: .
      outputs:
      - name: image
      params:
        CONTEXT: .
      run:
        path: build

  - put: simple-image
    params:
      image: image


  # - get: concourse-docs-git
  #   trigger: true
  #   params:
  #     depth: 1
  #     submodules: none
  #     submodules_depth: 0
  #     clean_tags: true
  #     clean_submodules: true
  #     tag_filter: ''
  #     paths:
  #       - .
  #     disable_lfs: true
  #     target: /tmp
  # - task: build-docker-image
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source: {repository: docker}
  #     inputs:
  #     - name: source-code
  #     run:
  #       path: source-code/build.sh


  - task: build-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: your-docker-repo/image-name
          tag: latest  # or specify the appropriate tag
      inputs:
      - name: source-code
      run:
        path: /bin/sh
        args:
          - -exc
          - |
            cd source-code
            ./build.sh  # Adjust the path and name of the script as needed



  # - task: sign-docker-image
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source: {repository: docker}
  #     inputs:
  #     - name: source-code
  #     params:
  #       SIGNING_KEY_URI: ((SIGNING_KEY_URI))
  #       SIGNING_CERT_URI: ((SIGNING_CERT_URI))
  #     run:
  #       path: source-code/sign.sh


