resources:
- name: source-code
  type: git
  source:
    uri: <URL_TO_YOUR_GIT_REPO>
    branch: main

jobs:
- name: build-and-sign-docker-image
  plan:
  - get: source-code
    trigger: true
  - task: build-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: docker}
      inputs:
      - name: source-code
      run:
        path: source-code/build.sh
  - task: sign-docker-image
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: docker}
      inputs:
      - name: source-code
      params:
        SIGNING_KEY_URI: ((SIGNING_KEY_URI))
        SIGNING_CERT_URI: ((SIGNING_CERT_URI))
      run:
        path: source-code/sign.sh
