resources:
- name: source-code
  type: git
  icon: github
  source:
    uri: https://github.com/ExitoLab/codementor_concourse_ci_azure.git
    branch: main

# - name: docker-image
#   type: docker-image
#   source:
#     username: {{registry-username}}
#     password: {{registry-password}}
#     repository: {{image-repo-name}}

jobs:
- name: build-and-use-image
  plan:
  - get:  source-code
    trigger: true

  - task: run-script
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: /bin/sh
        args:
          - -exc
          - |
            # Your script commands go here
            echo "Hello, world!"
            # Additional commands...

  # - task: build-task-image
  #   privileged: true
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: registry-image
  #       source:
  #         # Check out the README for oci-build-task at
  #         # https://github.com/concourse/oci-build-task
  #         repository: concourse/oci-build-task
  #     inputs:
  #     - name: source-code
  #     outputs:
  #     - name: image
  #     params:
  #       CONTEXT: .
  #       UNPACK_ROOTFS: "true" # only needed if using image in a future step
  #     run:
  #       path: build



# jobs:
# - name: build-and-publish-sign-image
#   plan:
#   - get: source-code
#     trigger: true
#   - put: docker-image
#     params:
#       build: .


  # - task: build
  #   privileged: true
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: registry-image
  #       source:
  #         repository: concourse/oci-build-task
  #     inputs:
  #     - name: source-code
  #       path: .
  #     outputs:
  #     - name: image
  #     params:
  #       CONTEXT: .
  #     run:
  #       path: build



  # - get: concourse-docs-git
  #   trigger: true
  #   params:
  #     depth: 1
  #     submodules: none
  #     submodules_depth: 0
  #     clean_tags: true
  #     clean_submodules: true
  #     tag_filter: ''
  #     paths:
  #       - .
  #     disable_lfs: true
  #     target: /tmp
  # - task: build-docker-image
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source: {repository: docker}
  #     inputs:
  #     - name: source-code
  #     run:
  #       path: source-code/build.sh

  # - task: build-docker-image
  #   config:
  #     platform: linux
  #     image_resource:
  #       type: docker-image
  #       source:
  #         repository: your-docker-repo/image-name
  #         tag: latest  # or specify the appropriate tag
  #     inputs:
  #     - name: source-code
  #     run:
  #       path: /bin/sh
  #       args:
  #         - -exc
  #         - |
  #           cd source-code
  #           ./build.sh  # Adjust the path and name of the script as needed