jobs:
- name: hello
  plan:
  - task: simple-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: /bin/sh
        args:
          - -exc
          - echo "Hello, world!"
